apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateless-api
  template:
    metadata:
      labels:
        app: stateless-api
    spec:
      containers:
        - name: stateless-api
          image: 285982079759.dkr.ecr.us-east-1.amazonaws.com/stateless-repo:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: stateless-api-service
spec:
  selector:
    app: stateless-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
